project:
  name: "CI"
  metadata:
    message: "Hello World!"
  # Using docker-compose service names
  # https://docs.docker.com/compose/networking/
  server:
    dbAddress: "alpha:9080"
    rpcAddress: "master:50051"
  analysis:
    - analyzer: scancode-analyzer
      name: "Scancode Analyzer"
      config:
        workdir: "/var/qmstr/buildroot"
        resultfile: "/var/qmstr/buildroot/scancode.json"
